# frozen_string_literal: true

module Lacold
  module Adapters
    class BTop < Base
      def id = "btop"
      def name = "BTop"
      def description = "BTop resource monitor themes"

      def render(themes)
        files = themes.map { |theme| output("btop/#{theme.id}.theme", btop_theme(theme)) }
        files << output("btop/README.md", <<~MARKDOWN)
          # Lacold for BTop

          Copy a `.theme` file to `~/.config/btop/themes/`, then select its
          filename from BTop's `color_theme` setting.
        MARKDOWN
      end

      private

      def btop_theme(theme)
        values = {
          main_bg: theme.bg, main_fg: theme.fg, title: theme.primary,
          hi_fg: theme.strong, selected_bg: theme.selection,
          selected_fg: theme.fg, inactive_fg: theme.muted,
          graph_text: theme.secondary, meter_bg: theme.raised,
          proc_misc: theme.accent_secondary, cpu_box: theme.primary,
          mem_box: theme.accent_secondary, net_box: theme.accent_faint,
          proc_box: theme.strong, div_line: theme.border,
          temp_start: theme.accent_faint, temp_mid: theme.primary,
          temp_end: theme.strong, cpu_start: theme.accent_faint,
          cpu_mid: theme.primary, cpu_end: theme.strong,
          free_start: theme.accent_faint, free_mid: theme.primary,
          free_end: theme.strong, cached_start: theme.accent_faint,
          cached_mid: theme.primary, cached_end: theme.strong,
          available_start: theme.accent_faint, available_mid: theme.primary,
          available_end: theme.strong, used_start: theme.accent_faint,
          used_mid: theme.primary, used_end: theme.strong,
          download_start: theme.accent_faint, download_mid: theme.primary,
          download_end: theme.strong, upload_start: theme.accent_faint,
          upload_mid: theme.primary, upload_end: theme.strong
        }
        (["# #{theme.name} — generated by Lacold #{Lacold::VERSION}"] +
          values.map { |key, value| "theme[#{key}]=\"#{value}\"" }).join("\n")
      end
    end
  end
end
