# frozen_string_literal: true

module Lacold
  module Adapters
    class DrRacket < Base
      def id = "dr-racket"
      def name = "DrRacket"
      def description = "DrRacket info.rkt color-scheme packages"

      def render(themes)
        files = themes.map { |theme| output("dr-racket/#{theme.id}/info.rkt", info(theme)) }
        files << output("dr-racket/README.md", <<~MARKDOWN)
          # Lacold for DrRacket

          Install the selected directory as a local Racket package with
          `raco pkg install ./lacold-air-blue-dark`, run `raco setup`, restart
          DrRacket, and select the scheme in Colors preferences.
        MARKDOWN
      end

      private

      def vector(hex)
        "#(#{rgb_line(hex)})"
      end

      def info(theme)
        colors = {
          "framework:default-text-color" => theme.fg,
          "framework:default-background-color" => theme.bg,
          "framework:syntax-color:scheme:symbol" => theme.fg,
          "framework:syntax-color:scheme:keyword" => theme.primary,
          "framework:syntax-color:scheme:comment" => theme.muted,
          "framework:syntax-color:scheme:string" => theme.fg,
          "framework:syntax-color:scheme:constant" => theme.accent_secondary,
          "framework:syntax-color:scheme:parenthesis" => theme.primary,
          "framework:syntax-color:scheme:error" => theme.red,
          "framework:syntax-color:scheme:hash-colon-keyword" => theme.primary
        }
        entries = colors.map { |key, value| "           (#{key} #{vector(value)})" }.join("\n")
        <<~RACKET
          #lang info
          ;; #{theme.name} — generated by Lacold #{Lacold::VERSION}
          (define framework:color-schemes
            '(#hash((name . "#{theme.name}")
                    (colors . (
          #{entries})))))
        RACKET
      end
    end
  end
end
