# frozen_string_literal: true

module Lacold
  module Adapters
    class DrRacket < Base
      def id = "dr-racket"
      def name = "DrRacket"
      def description = "DrRacket info.rkt color-scheme packages"

      def render(themes)
        files = themes.map { |theme| output("dr-racket/#{theme.id}/info.rkt", info(theme)) }
        files << target_readme
      end

      private

      def vector(hex)
        "#(#{rgb_line(hex)})"
      end

      def info(theme)
        colors = {
          "framework:default-text-color" => theme.fg,
          "framework:default-background-color" => theme.bg,
          "framework:syntax-color:scheme:symbol" => theme.syntax_color(:symbol, theme.fg),
          "framework:syntax-color:scheme:keyword" => theme.syntax_color(:keyword, theme.primary),
          "framework:syntax-color:scheme:comment" => theme.muted,
          "framework:syntax-color:scheme:string" => theme.syntax_color(:string, theme.fg),
          "framework:syntax-color:scheme:constant" => theme.syntax_color(:constant, theme.accent_secondary),
          "framework:syntax-color:scheme:parenthesis" => theme.syntax_color(:punctuation, theme.primary),
          "framework:syntax-color:scheme:error" => theme.red,
          "framework:syntax-color:scheme:hash-colon-keyword" => theme.syntax_color(:label, theme.primary)
        }
        entries = colors.map { |key, value| "           (#{key} #{vector(value)})" }.join("\n")
        <<~RACKET
          #lang info
          ;; #{theme.name} — generated by Lacold #{Lacold::VERSION}
          (define framework:color-schemes
            '(#hash((name . "#{theme.name}")
                    (colors . (
          #{entries})))))
        RACKET
      end
    end
  end
end
