# frozen_string_literal: true

module Lacold
  module Adapters
    class Emacs < Base
      def id = "emacs"
      def name = "Emacs"
      def description = "Emacs custom themes"

      def render(themes)
        files = themes.map { |theme| output("emacs/#{theme.id}-theme.el", emacs_theme(theme)) }
        files << output("emacs/README.md", <<~MARKDOWN)
          # Lacold for Emacs

          Copy theme files into a directory in `custom-theme-load-path`, then
          run `(load-theme 'lacold-air-blue-dark t)`.
        MARKDOWN
      end

      private

      def emacs_theme(theme)
        faces = {
          default: "((t (:foreground \"#{theme.fg}\" :background \"#{theme.bg}\")))",
          cursor: "((t (:background \"#{theme.primary}\")))",
          fringe: "((t (:foreground \"#{theme.muted}\" :background \"#{theme.bg}\")))",
          region: "((t (:foreground \"#{theme.fg}\" :background \"#{theme.selection}\")))",
          highlight: "((t (:background \"#{theme.wash}\")))",
          hl_line: "((t (:background \"#{theme.line}\")))",
          mode_line: "((t (:foreground \"#{theme.fg}\" :background \"#{theme.raised}\" :box (:color \"#{theme.border}\"))))",
          mode_line_inactive: "((t (:foreground \"#{theme.muted}\" :background \"#{theme.surface}\")))",
          minibuffer_prompt: "((t (:foreground \"#{theme.primary}\" :weight bold)))",
          font_lock_builtin_face: "((t (:foreground \"#{theme.accent_secondary}\")))",
          font_lock_comment_face: "((t (:foreground \"#{theme.muted}\" :slant italic)))",
          font_lock_constant_face: "((t (:foreground \"#{theme.fg}\")))",
          font_lock_function_name_face: "((t (:foreground \"#{theme.fg}\" :weight bold)))",
          font_lock_keyword_face: "((t (:foreground \"#{theme.primary}\")))",
          font_lock_string_face: "((t (:foreground \"#{theme.fg}\")))",
          font_lock_type_face: "((t (:foreground \"#{theme.accent_secondary}\")))",
          font_lock_variable_name_face: "((t (:foreground \"#{theme.fg}\")))",
          font_lock_warning_face: "((t (:foreground \"#{theme.strong}\" :underline t)))",
          error: "((t (:foreground \"#{theme.strong}\" :underline t)))",
          warning: "((t (:foreground \"#{theme.accent_secondary}\" :weight bold)))",
          success: "((t (:foreground \"#{theme.primary}\" :weight bold)))",
          link: "((t (:foreground \"#{theme.primary}\" :underline t)))",
          line_number: "((t (:foreground \"#{theme.line_nr}\" :background \"#{theme.bg}\")))",
          line_number_current_line: "((t (:foreground \"#{theme.line_nr_active}\" :background \"#{theme.line}\" :weight bold)))"
        }
        declarations = faces.map { |face, spec| "   '(#{face.to_s.tr("_", "-")} #{spec})" }.join("\n")
        <<~ELISP
          ;;; #{theme.id}-theme.el --- #{theme.name} -*- lexical-binding: t; -*-
          ;; Generated by Lacold #{Lacold::VERSION}. Do not edit generated releases.
          (deftheme #{theme.id} "#{theme.name}")
          (custom-theme-set-faces
           '#{theme.id}
          #{declarations})
          (provide-theme '#{theme.id})
          ;;; #{theme.id}-theme.el ends here
        ELISP
      end
    end
  end
end
