# frozen_string_literal: true

module Lacold
  module Adapters
    class Emacs < Base
      def id = "emacs"
      def name = "Emacs"
      def description = "Emacs custom themes"

      def render(themes)
        files = themes.map { |theme| output("emacs/#{theme.id}-theme.el", emacs_theme(theme)) }
        files << output("emacs/README.md", <<~MARKDOWN)
          # Lacold for Emacs

          Copy theme files into a directory in `custom-theme-load-path`, then
          run `(load-theme 'lacold-air-blue-dark t)`. Themes cover core Emacs,
          Font Lock, search, completion, Diff, VC, compilation, Flymake, Dired,
          shells, Org, Magit, Corfu, Company, and Vertico faces.
        MARKDOWN
      end

      private

      def emacs_theme(theme)
        faces = core_faces(theme)
          .merge(font_lock_faces(theme))
          .merge(completion_faces(theme))
          .merge(tool_faces(theme))
          .merge(org_faces(theme))
          .merge(package_faces(theme))

        theme.ansi.each do |name, color|
          faces[:"ansi_color_#{name}"] = face(theme, color)
        end
        declarations = faces.map { |face, spec| "   '(#{face.to_s.tr("_", "-")} #{spec})" }.join("\n")
        <<~ELISP
          ;;; #{theme.id}-theme.el --- #{theme.name} -*- lexical-binding: t; -*-
          ;; Generated by Lacold #{Lacold::VERSION}. Do not edit generated releases.
          (deftheme #{theme.id} "#{theme.name}"
            :family 'lacold :kind 'color-scheme :background-mode '#{theme.mode})
          (custom-theme-set-faces
           '#{theme.id}
          #{declarations})
          (provide-theme '#{theme.id})
          ;;; #{theme.id}-theme.el ends here
        ELISP
      end

      def core_faces(theme)
        {
          default: face(theme, :fg, background: :bg),
          fixed_pitch: face(theme, inherit: :default),
          fixed_pitch_serif: face(theme, inherit: :default, family: "Serif"),
          variable_pitch: face(theme, :fg, background: :bg),
          cursor: face(theme, :bg, background: :caret),
          fringe: face(theme, :muted, background: :bg),
          region: face(theme, :fg, background: :selection, extend: true),
          secondary_selection: face(theme, :fg, background: :inactive_selection, extend: true),
          highlight: face(theme, background: :wash),
          hl_line: face(theme, background: :line, extend: true),
          shadow: face(theme, :muted),
          escape_glyph: face(theme, :orange),
          homoglyph: face(theme, :orange),
          nobreak_hyphen: face(theme, :accent_faint, underline: true),
          nobreak_space: face(theme, :accent_faint, underline: true),
          trailing_whitespace: face(theme, background: :red_wash),
          vertical_border: face(theme, :border),
          window_divider: face(theme, :border),
          window_divider_first_pixel: face(theme, :border),
          window_divider_last_pixel: face(theme, :border),
          header_line: face(theme, :secondary, background: :surface, box: nil),
          header_line_highlight: face(theme, :fg, background: :selection),
          mode_line: face(theme, :fg, background: :raised, box: nil),
          mode_line_active: face(theme, inherit: :mode_line),
          mode_line_inactive: face(theme, :muted, background: :surface, box: nil),
          mode_line_buffer_id: face(theme, :fg, weight: :bold),
          mode_line_emphasis: face(theme, :primary, weight: :bold),
          mode_line_highlight: face(theme, :fg, background: :selection),
          tab_bar: face(theme, :muted, background: :surface, box: nil),
          tab_bar_tab: face(theme, :fg, background: :bg, weight: :bold, box: nil),
          tab_bar_tab_inactive: face(theme, :muted, background: :surface, box: nil),
          tab_line: face(theme, :muted, background: :surface, box: nil),
          tab_line_tab_current: face(theme, :fg, background: :bg, weight: :bold, box: nil),
          tab_line_tab_inactive: face(theme, :muted, background: :surface, box: nil),
          tab_line_tab_inactive_alternate: face(theme, :muted, background: :raised, box: nil),
          tab_line_close_highlight: face(theme, :red),
          minibuffer_prompt: face(theme, :primary, weight: :bold),
          minibuffer_nonselected: face(theme, :muted, background: :surface),
          read_multiple_choice_face: face(theme, :primary, background: :wash, weight: :bold),
          line_number: face(theme, :line_nr, background: :bg),
          line_number_current_line: face(theme, :line_nr_active, background: :line, weight: :bold),
          link: face(theme, :primary, underline: true),
          link_visited: face(theme, :accent_secondary, underline: true),
          button: face(theme, :primary, underline: true, weight: :bold),
          tooltip: face(theme, :fg, background: :surface),
          menu: face(theme, :fg, background: :surface),
          help_key_binding: face(theme, :primary, background: :wash, box: {color: theme.border}),
          separator_line: face(theme, :border),
          which_func: face(theme, :accent_secondary),
          custom_comment: face(theme, :secondary, background: :wash),
          widget_button: face(theme, :primary, weight: :bold),
          widget_button_pressed: face(theme, :strong, weight: :bold),
          widget_documentation: face(theme, :muted),
          widget_field: face(theme, :fg, background: :surface, box: {color: theme.border}),
          widget_single_line_field: face(theme, :fg, background: :surface, box: {color: theme.border}),
          widget_inactive: face(theme, :faint),
          tool_bar: face(theme, :fg, background: :surface),
          custom_group_tag: face(theme, :primary, weight: :bold, height: 1.15),
          custom_state: face(theme, :green),
          custom_variable_tag: face(theme, :primary, weight: :bold),
          isearch: face(theme, :fg, background: :orange_wash, weight: :bold),
          isearch_fail: diagnostic_face(theme, :red, :red_wash),
          lazy_highlight: face(theme, :fg, background: :yellow_wash),
          match: face(theme, :fg, background: :yellow_wash, weight: :bold),
          query_replace: face(theme, :fg, background: :orange_wash, weight: :bold),
          show_paren_match: face(theme, :primary, background: :bracket, weight: :bold),
          show_paren_match_expression: face(theme, background: :bracket),
          show_paren_mismatch: diagnostic_face(theme, :red, :red_wash),
          next_error: face(theme, :fg, background: :selection, extend: true),
          next_error_message: face(theme, :fg, background: :wash, extend: true)
        }
      end

      def font_lock_faces(theme)
        {
          font_lock_bracket_face: face(theme, :secondary),
          font_lock_builtin_face: face(theme, :accent_secondary),
          font_lock_comment_face: face(theme, :muted, slant: :italic),
          font_lock_comment_delimiter_face: face(theme, :faint, slant: :italic),
          font_lock_constant_face: face(theme, :fg),
          font_lock_delimiter_face: face(theme, :secondary),
          font_lock_doc_face: face(theme, :muted, slant: :italic),
          font_lock_doc_markup_face: face(theme, :accent_secondary),
          font_lock_escape_face: face(theme, :orange),
          font_lock_function_call_face: face(theme, :fg),
          font_lock_function_name_face: face(theme, :fg),
          font_lock_keyword_face: face(theme, :primary),
          font_lock_misc_punctuation_face: face(theme, :secondary),
          font_lock_negation_char_face: face(theme, :secondary),
          font_lock_number_face: face(theme, :fg),
          font_lock_operator_face: face(theme, :secondary),
          font_lock_preprocessor_face: face(theme, :accent_secondary),
          font_lock_property_name_face: face(theme, :secondary),
          font_lock_property_use_face: face(theme, :secondary),
          font_lock_punctuation_face: face(theme, :secondary),
          font_lock_regexp_face: face(theme, :orange),
          font_lock_regexp_grouping_backslash: face(theme, :orange),
          font_lock_regexp_grouping_construct: face(theme, :orange),
          font_lock_string_face: face(theme, :fg),
          font_lock_type_face: face(theme, :accent_secondary),
          font_lock_variable_name_face: face(theme, :fg),
          font_lock_variable_use_face: face(theme, :fg),
          font_lock_warning_face: face(theme, :orange, weight: :semi_bold),
          elisp_condition: face(theme, :orange),
          elisp_major_mode_name: face(theme, :primary, weight: :bold),
          elisp_rx: face(theme, :accent_secondary),
          elisp_shorthand_font_lock_face: face(theme, :primary),
          elisp_symbol_at_mouse: face(theme, background: :wash),
          elisp_symbol_role: face(theme, :primary),
          elisp_symbol_role_definition: face(theme, :strong, weight: :bold),
          elisp_unknown_call: face(theme, :muted)
        }
      end

      def completion_faces(theme)
        {
          completions_annotations: face(theme, :muted, slant: :italic),
          completions_common_part: face(theme, :primary, weight: :bold),
          completions_first_difference: face(theme, :strong, weight: :bold),
          completions_group_separator: face(theme, :border),
          completions_group_title: face(theme, :fg, background: :raised, weight: :bold),
          completions_highlight: face(theme, :fg, background: :selection),
          completion_preview: face(theme, :muted),
          completion_preview_common: face(theme, :secondary),
          completion_preview_exact: face(theme, :primary),
          minibuffer_completion_help: face(theme, :muted),
          marginalia_documentation: face(theme, :muted, slant: :italic),
          marginalia_file_name: face(theme, :fg),
          marginalia_mode: face(theme, :accent_secondary),
          tooltip_selection: face(theme, :fg, background: :selection)
        }
      end

      def tool_faces(theme)
        faces = {
          error: diagnostic_face(theme, :red, :red_wash),
          warning: face(theme, :orange, weight: :bold),
          success: face(theme, :green, weight: :bold),
          compilation_column_number: face(theme, :muted),
          compilation_line_number: face(theme, :primary),
          compilation_error: diagnostic_face(theme, :red, :red_wash),
          compilation_warning: face(theme, :orange, weight: :bold),
          compilation_info: face(theme, :green),
          compilation_mode_line_run: face(theme, :primary, weight: :bold),
          compilation_mode_line_exit: face(theme, :primary, weight: :bold),
          compilation_mode_line_fail: face(theme, :red, weight: :bold),
          flymake_error: diagnostic_face(theme, :red, :red_wash),
          flymake_warning: diagnostic_face(theme, :orange, :orange_wash),
          flymake_note: diagnostic_face(theme, :primary),
          flycheck_error: diagnostic_face(theme, :red, :red_wash),
          flycheck_warning: diagnostic_face(theme, :orange, :orange_wash),
          flycheck_info: diagnostic_face(theme, :primary),
          grep_heading: face(theme, :fg, background: :raised, weight: :bold),
          diff_header: face(theme, :secondary, background: :surface),
          diff_file_header: face(theme, :fg, background: :raised, weight: :bold),
          diff_hunk_header: face(theme, :primary, background: :surface, weight: :bold),
          diff_context: face(theme, :muted),
          diff_added: face(theme, :green, background: :green_wash),
          diff_removed: face(theme, :red, background: :red_wash),
          diff_changed: face(theme, :primary, background: :wash),
          diff_refine_added: face(theme, :green, background: :green_wash, weight: :bold),
          diff_refine_removed: face(theme, :red, background: :red_wash, weight: :bold),
          diff_refine_changed: face(theme, :primary, background: :selection, weight: :bold),
          diff_indicator_added: face(theme, :green),
          diff_indicator_removed: face(theme, :red),
          diff_indicator_changed: face(theme, :primary),
          diff_error: diagnostic_face(theme, :red, :red_wash),
          vc_dir_header: face(theme, :fg, weight: :bold),
          vc_dir_header_value: face(theme, :primary),
          vc_dir_directory: face(theme, :primary, weight: :bold),
          vc_dir_file: face(theme, :fg),
          vc_dir_status_up_to_date: face(theme, :muted),
          vc_dir_status_edited: face(theme, :primary),
          vc_dir_status_warning: face(theme, :orange),
          vc_dir_status_ignored: face(theme, :faint),
          log_view_message: face(theme, :fg, weight: :bold),
          log_view_file: face(theme, :primary),
          log_view_commit_body: face(theme, :secondary),
          dired_header: face(theme, :fg, background: :raised, weight: :bold),
          dired_directory: face(theme, :primary, weight: :bold),
          dired_symlink: face(theme, :accent_secondary),
          dired_broken_symlink: diagnostic_face(theme, :red, :red_wash),
          dired_marked: face(theme, :fg, background: :selection, weight: :bold),
          dired_flagged: face(theme, :red, background: :red_wash),
          dired_mark: face(theme, :primary, weight: :bold),
          dired_ignored: face(theme, :faint),
          dired_special: face(theme, :accent_secondary),
          dired_warning: face(theme, :orange),
          comint_highlight_prompt: face(theme, :primary, weight: :bold),
          comint_highlight_input: face(theme, :fg, weight: :bold),
          eshell_prompt: face(theme, :primary, weight: :bold),
          eshell_ls_directory: face(theme, :primary, weight: :bold),
          eshell_ls_symlink: face(theme, :accent_secondary),
          eshell_ls_executable: face(theme, :fg, weight: :bold),
          eshell_ls_archive: face(theme, :secondary),
          eshell_ls_unreadable: face(theme, :faint),
          eshell_ls_missing: face(theme, :red),
          ansi_color_bold: face(theme, weight: :bold),
          ansi_color_faint: face(theme, :muted),
          ansi_color_italic: face(theme, slant: :italic),
          ansi_color_underline: face(theme, underline: true)
        }
        faces
      end

      def org_faces(theme)
        faces = {
          org_default: face(theme, :fg, background: :bg),
          org_document_title: face(theme, :strong, weight: :bold, height: 1.3),
          org_document_info: face(theme, :primary),
          org_document_info_keyword: face(theme, :muted),
          org_meta_line: face(theme, :muted),
          org_special_keyword: face(theme, :secondary),
          org_drawer: face(theme, :secondary),
          org_property_value: face(theme, :fg),
          org_block: face(theme, :fg, background: :surface, extend: true, inherit: :fixed_pitch),
          org_block_begin_line: face(theme, :faint, background: :surface, extend: true),
          org_block_end_line: face(theme, :faint, background: :surface, extend: true),
          org_inline_src_block: face(theme, :fg, background: :surface, inherit: :fixed_pitch),
          org_code: face(theme, :fg, inherit: :fixed_pitch),
          org_verbatim: face(theme, :accent_secondary, inherit: :fixed_pitch),
          org_quote: face(theme, :muted, slant: :italic),
          org_table: face(theme, :accent_secondary),
          org_table_header: face(theme, :primary, weight: :bold),
          org_formula: face(theme, :primary),
          org_link: face(theme, :primary, underline: true),
          org_tag: face(theme, :secondary, weight: :bold),
          org_todo: face(theme, :orange, weight: :bold),
          org_done: face(theme, :green, weight: :bold),
          org_headline_todo: face(theme, :orange),
          org_headline_done: face(theme, :muted),
          org_checkbox: face(theme, :primary, weight: :bold),
          org_checkbox_statistics_todo: face(theme, :orange),
          org_checkbox_statistics_done: face(theme, :green),
          org_date: face(theme, :accent_secondary, underline: true),
          org_ellipsis: face(theme, :faint),
          org_warning: diagnostic_face(theme, :red, :red_wash),
          org_priority: face(theme, :orange, weight: :bold),
          org_agenda_structure: face(theme, :fg, background: :raised, weight: :bold),
          org_agenda_date: face(theme, :primary, weight: :bold),
          org_agenda_date_today: face(theme, :fg, weight: :bold),
          org_agenda_date_weekend: face(theme, :accent_secondary),
          org_agenda_done: face(theme, :muted),
          org_scheduled: face(theme, :primary),
          org_scheduled_today: face(theme, :green),
          org_scheduled_previously: face(theme, :orange),
          org_upcoming_deadline: face(theme, :orange),
          org_imminent_deadline: face(theme, :red, weight: :bold),
          org_time_grid: face(theme, :faint)
        }
        [[:primary, :bold, 1.20], [:secondary, :semi_bold, 1.15],
         [:secondary, :normal, 1.10], [:muted, :semi_bold, 1.05],
         [:muted, :normal, 1.0], [:muted, :normal, 1.0],
         [:faint, :normal, 1.0], [:faint, :normal, 1.0]].each_with_index do |(color, weight, height), index|
          faces[:"org_level_#{index + 1}"] = face(theme, color, weight: weight, height: height)
        end
        faces
      end

      def package_faces(theme)
        {
          corfu_default: face(theme, :fg, background: :surface),
          corfu_current: face(theme, :fg, background: :selection),
          corfu_border: face(theme, background: :border),
          corfu_bar: face(theme, background: :muted),
          corfu_annotations: face(theme, :muted, slant: :italic),
          company_tooltip: face(theme, :fg, background: :surface),
          company_tooltip_selection: face(theme, :fg, background: :selection),
          company_tooltip_common: face(theme, :primary, weight: :bold),
          company_tooltip_common_selection: face(theme, :strong, weight: :bold),
          company_tooltip_annotation: face(theme, :muted),
          company_scrollbar_bg: face(theme, background: :raised),
          company_scrollbar_fg: face(theme, background: :muted),
          company_preview: face(theme, :muted),
          company_preview_common: face(theme, :primary),
          vertico_current: face(theme, :fg, background: :selection, extend: true),
          vertico_group_title: face(theme, :fg, background: :raised, weight: :bold),
          vertico_group_separator: face(theme, :border, strike_through: true),
          orderless_match_face_0: face(theme, :primary, weight: :bold),
          orderless_match_face_1: face(theme, :accent_secondary, weight: :bold),
          orderless_match_face_2: face(theme, :strong, weight: :bold),
          orderless_match_face_3: face(theme, :secondary, weight: :bold),
          magit_section_heading: face(theme, :fg, background: :raised, weight: :bold),
          magit_section_highlight: face(theme, background: :line),
          magit_branch_current: face(theme, :strong, weight: :bold, box: {color: theme.strong}),
          magit_branch_local: face(theme, :primary),
          magit_branch_remote: face(theme, :green),
          magit_tag: face(theme, :yellow, weight: :bold),
          magit_hash: face(theme, :faint),
          magit_diff_file_heading: face(theme, :fg, weight: :bold),
          magit_diff_file_heading_highlight: face(theme, :fg, background: :raised, weight: :bold),
          magit_diff_hunk_heading: face(theme, :secondary, background: :surface),
          magit_diff_hunk_heading_highlight: face(theme, :primary, background: :raised, weight: :bold),
          magit_diff_context: face(theme, :muted),
          magit_diff_context_highlight: face(theme, :secondary, background: :line),
          magit_diff_added: face(theme, :green, background: :green_wash),
          magit_diff_added_highlight: face(theme, :green, background: :green_wash, weight: :bold),
          magit_diff_removed: face(theme, :red, background: :red_wash),
          magit_diff_removed_highlight: face(theme, :red, background: :red_wash, weight: :bold),
          magit_diffstat_added: face(theme, :green),
          magit_diffstat_removed: face(theme, :red),
          magit_process_ok: face(theme, :green, weight: :bold),
          magit_process_ng: face(theme, :red, weight: :bold),
          magit_signature_good: face(theme, :green),
          magit_signature_bad: face(theme, :red)
        }.merge(markdown_faces(theme))
          .merge(magit_extra_faces(theme))
          .merge(workbench_package_faces(theme))
      end

      def markdown_faces(theme)
        faces = {
          markdown_header_face: face(theme, :strong, weight: :bold),
          markdown_header_delimiter_face: face(theme, :faint),
          markdown_header_rule_face: face(theme, :border),
          markdown_markup_face: face(theme, :faint),
          markdown_bold_face: face(theme, :fg, weight: :bold),
          markdown_italic_face: face(theme, :fg, slant: :italic),
          markdown_code_face: face(theme, :fg, background: :surface, inherit: :fixed_pitch),
          markdown_inline_code_face: face(theme, :fg, background: :surface, inherit: :fixed_pitch),
          markdown_pre_face: face(theme, :fg, background: :surface, inherit: :fixed_pitch),
          markdown_blockquote_face: face(theme, :muted, slant: :italic),
          markdown_comment_face: face(theme, :muted, slant: :italic),
          markdown_highlight_face: face(theme, :fg, background: :wash),
          markdown_highlighting_face: face(theme, :fg, background: :wash),
          markdown_hr_face: face(theme, :border),
          markdown_link_face: face(theme, :primary, underline: true),
          markdown_plain_url_face: face(theme, :primary, underline: true),
          markdown_url_face: face(theme, :accent_secondary),
          markdown_link_title_face: face(theme, :muted),
          markdown_list_face: face(theme, :primary),
          markdown_table_face: face(theme, :accent_secondary, inherit: :fixed_pitch),
          markdown_language_info_face: face(theme, :muted),
          markdown_language_keyword_face: face(theme, :accent_secondary),
          markdown_metadata_key_face: face(theme, :primary),
          markdown_metadata_value_face: face(theme, :fg),
          markdown_missing_link_face: diagnostic_face(theme, :red, :red_wash),
          markdown_strike_through_face: face(theme, :muted, strike_through: true)
        }
        [[:strong, 1.20], [:primary, 1.15], [:accent_secondary, 1.10],
         [:fg, 1.05], [:secondary, 1.0], [:muted, 1.0]].each_with_index do |(color, height), index|
          faces[:"markdown_header_face_#{index + 1}"] = face(theme, color, weight: :bold, height: height)
        end
        faces
      end

      def magit_extra_faces(theme)
        {
          magit_bisect_bad: face(theme, :strong, weight: :bold),
          magit_bisect_good: face(theme, :primary, weight: :bold),
          magit_bisect_skip: face(theme, :accent_secondary, weight: :bold),
          magit_blame_heading: face(theme, :fg, background: :raised),
          magit_blame_highlight: face(theme, :fg, background: :raised),
          magit_blame_hash: face(theme, :faint),
          magit_blame_name: face(theme, :primary),
          magit_blame_date: face(theme, :muted),
          magit_blame_summary: face(theme, :secondary),
          magit_branch_upstream: face(theme, :accent_secondary),
          magit_branch_warning: face(theme, :orange),
          magit_cherry_equivalent: face(theme, :accent_secondary),
          magit_cherry_unmatched: face(theme, :primary),
          magit_diff_added_indicator: face(theme, :green),
          magit_diff_removed_indicator: face(theme, :red),
          magit_diff_base: face(theme, :primary, background: :wash),
          magit_diff_base_highlight: face(theme, :primary, background: :selection),
          magit_diff_base_indicator: face(theme, :primary),
          magit_diff_file_heading_selection: face(theme, :fg, background: :selection, weight: :bold),
          magit_diff_hunk_heading_selection: face(theme, :fg, background: :selection, weight: :bold),
          magit_diff_lines_heading: face(theme, :fg, background: :strong, weight: :bold),
          magit_diff_our_heading: face(theme, :red, background: :red_wash),
          magit_diff_their_heading: face(theme, :green, background: :green_wash),
          magit_filename: face(theme, :fg),
          magit_head: face(theme, :strong, weight: :bold),
          magit_log_author: face(theme, :primary),
          magit_log_date: face(theme, :muted),
          magit_log_graph: face(theme, :secondary),
          magit_refname: face(theme, :accent_secondary),
          magit_refname_pullreq: face(theme, :primary),
          magit_refname_stash: face(theme, :secondary),
          magit_refname_wip: face(theme, :muted),
          magit_section_child_count: face(theme, :muted),
          magit_section_heading_selection: face(theme, :fg, background: :selection, weight: :bold),
          magit_section_secondary_heading: face(theme, :accent_secondary, weight: :bold),
          magit_sequence_drop: face(theme, :red, strike_through: true),
          magit_sequence_head: face(theme, :strong, weight: :bold),
          magit_sequence_part: face(theme, :accent_secondary),
          magit_sequence_pick: face(theme, :fg),
          magit_sequence_stop: face(theme, :red),
          magit_reflog_amend: face(theme, :accent_secondary),
          magit_reflog_checkout: face(theme, :primary),
          magit_reflog_cherry_pick: face(theme, :primary),
          magit_reflog_commit: face(theme, :primary),
          magit_reflog_merge: face(theme, :primary),
          magit_reflog_other: face(theme, :accent_secondary),
          magit_reflog_rebase: face(theme, :accent_secondary),
          magit_reflog_remote: face(theme, :accent_secondary),
          magit_reflog_reset: face(theme, :red),
          magit_signature_error: face(theme, :red),
          magit_signature_expired: face(theme, :orange),
          magit_signature_expired_key: face(theme, :orange),
          magit_signature_revoked: face(theme, :red),
          magit_signature_untrusted: face(theme, :secondary)
        }
      end

      def workbench_package_faces(theme)
        {
          corfu_deprecated: face(theme, :muted, strike_through: true),
          corfu_echo: face(theme, :muted),
          corfu_indexed: face(theme, :primary, weight: :bold),
          corfu_popupinfo: face(theme, :fg, background: :surface),
          corfu_quick1: face(theme, :strong, weight: :bold),
          corfu_quick2: face(theme, :accent_secondary, weight: :bold),
          vertico_multiline: face(theme, :muted),
          vertico_quick1: face(theme, :strong, weight: :bold),
          vertico_quick2: face(theme, :accent_secondary, weight: :bold),
          dired_sidebar_face: face(theme, :fg, background: :surface),
          dired_subtree_depth_1_face: face(theme, background: :surface),
          dired_subtree_depth_2_face: face(theme, background: :raised),
          dired_subtree_depth_3_face: face(theme, background: :line),
          dired_subtree_depth_4_face: face(theme, background: :surface),
          dired_subtree_depth_5_face: face(theme, background: :raised),
          dired_subtree_depth_6_face: face(theme, background: :line),
          org_agenda_dimmed_todo_face: face(theme, :muted),
          org_hide: face(theme, :bg),
          org_mode_line_clock_overrun: face(theme, :red, background: :red_wash, weight: :bold),
          org_modern_label: face(theme, :fg, background: :surface),
          org_modern_block_name: face(theme, :accent_secondary),
          org_modern_date_active: face(theme, :fg, background: :selection),
          org_modern_date_inactive: face(theme, :muted, background: :surface),
          org_modern_done: face(theme, :green, background: :green_wash),
          org_modern_habit: face(theme, :green, background: :green_wash),
          org_modern_horizontal_rule: face(theme, :border),
          org_modern_internal_target: face(theme, :primary, background: :wash),
          org_modern_priority: face(theme, :orange, background: :orange_wash, weight: :bold),
          org_modern_progress_complete: face(theme, :fg, background: :primary),
          org_modern_progress_incomplete: face(theme, :fg, background: :surface),
          org_modern_radio_target: face(theme, :primary, background: :wash),
          org_modern_symbol: face(theme, :primary),
          org_modern_tag: face(theme, :secondary, background: :inactive_selection),
          org_modern_time_active: face(theme, :fg, background: :primary),
          org_modern_time_inactive: face(theme, :muted, background: :surface),
          org_modern_todo: face(theme, :orange, background: :orange_wash, weight: :bold),
          racket_debug_break_expression_face: diagnostic_face(theme, :red, :red_wash),
          racket_doc_link_face: face(theme, :primary, underline: true),
          racket_doc_litchar_face: face(theme, :accent_secondary, background: :surface, inherit: :fixed_pitch),
          racket_ext_link_face: face(theme, :primary, underline: true),
          racket_keyword_argument_face: face(theme, :primary),
          racket_paren_face: face(theme, :secondary),
          racket_repl_prompt: face(theme, :primary, weight: :bold),
          racket_selfeval_face: face(theme, :accent_secondary),
          racket_xp_error_face: diagnostic_face(theme, :red, :red_wash),
          racket_xp_unused_face: face(theme, :muted, strike_through: true),
          transient_disabled_suffix: face(theme, :red, background: :red_wash),
          transient_enabled_suffix: face(theme, :primary, background: :wash),
          transient_key: face(theme, :accent_secondary, weight: :bold),
          transient_key_exit: face(theme, :red, weight: :bold),
          transient_key_recurse: face(theme, :primary, weight: :bold),
          transient_key_return: face(theme, :accent_secondary, weight: :bold),
          transient_mismatched_key: face(theme, :red, underline: true),
          transient_nonstandard_key: face(theme, :secondary),
          smerge_base: face(theme, :primary, background: :wash),
          smerge_lower: face(theme, :green, background: :green_wash),
          smerge_markers: face(theme, :muted, background: :surface),
          smerge_refined_changed: face(theme, :fg, background: :selection),
          smerge_refined_added: face(theme, :green, background: :green_wash),
          smerge_refined_removed: face(theme, :red, background: :red_wash),
          smerge_upper: face(theme, :red, background: :red_wash),
          shr_h1: face(theme, :strong, weight: :bold, height: 1.2),
          shr_h2: face(theme, :primary, weight: :bold, height: 1.15),
          shr_h3: face(theme, :accent_secondary, weight: :bold, height: 1.1),
          shr_h4: face(theme, :fg, weight: :bold),
          shr_h5: face(theme, :secondary, weight: :bold),
          shr_h6: face(theme, :muted, weight: :bold),
          shr_mark: face(theme, :strong, background: :wash),
          shr_selected_link: face(theme, :fg, background: :selection, underline: true),
          shr_strike_through: face(theme, :muted, strike_through: true),
          anzu_mode_line: face(theme, :primary, weight: :bold),
          anzu_mode_line_no_match: face(theme, :strong, weight: :bold),
          ibuffer_locked_buffer: face(theme, :accent_secondary)
        }
      end

      def diagnostic_face(theme, color, wash = :wash)
        face(theme, color, background: wash, underline: {color: theme.public_send(color), style: :wave})
      end

      def face(theme, foreground = nil, background: nil, **attributes)
        properties = {}
        properties[:foreground] = resolve_color(theme, foreground) if foreground
        properties[:background] = resolve_color(theme, background) if background
        properties.merge!(attributes)
        "((t (#{properties.map { |key, value| ":#{key.to_s.tr('_', '-')} #{elisp(value)}" }.join(' ')})))"
      end

      def resolve_color(theme, value)
        value.is_a?(Symbol) ? theme.public_send(value) : value
      end

      def elisp(value)
        case value
        when String then value.inspect
        when Symbol then value.to_s.tr("_", "-")
        when Hash
          "(#{value.map { |key, item| ":#{key.to_s.tr('_', '-')} #{elisp(item)}" }.join(' ')})"
        when TrueClass then "t"
        when FalseClass, NilClass then "nil"
        else value.to_s
        end
      end
    end
  end
end
