# frozen_string_literal: true

module Lacold
  module Adapters
    class Fish < Base
      def id = "fish"
      def name = "Fish"
      def description = "Fish shell color configuration"

      def render(themes)
        files = themes.map { |theme| output("fish/#{theme.id}.fish", fish_theme(theme)) }
        files << target_readme
      end

      private

      def fish_theme(theme)
        colors = {
          fish_color_normal: theme.fg,
          fish_color_command: "#{theme.syntax_color(:keyword, theme.primary)} --bold",
          fish_color_keyword: theme.syntax_color(:keyword, theme.primary),
          fish_color_quote: theme.syntax_color(:string, theme.green),
          fish_color_redirection: theme.syntax_color(:preprocessor, theme.accent_secondary),
          fish_color_end: theme.syntax_color(:punctuation, theme.secondary),
          fish_color_error: theme.red,
          fish_color_param: theme.syntax_color(:variable, theme.fg),
          fish_color_option: theme.syntax_color(:attribute, theme.accent_secondary),
          fish_color_comment: "#{theme.muted} --italics",
          fish_color_selection: "#{theme.selection_fg} --background=#{bare(theme.selection)}",
          fish_color_operator: theme.syntax_color(:operator, theme.secondary),
          fish_color_escape: theme.syntax_color(:escape, theme.orange),
          fish_color_autosuggestion: theme.faint,
          fish_color_cancel: "#{theme.red} --reverse",
          fish_color_search_match: "#{theme.selection_fg} --background=#{bare(theme.yellow_wash)}",
          fish_color_history_current: "#{theme.primary} --bold",
          fish_color_valid_path: "#{theme.accent_secondary} --underline=single",
          fish_color_cwd: theme.primary,
          fish_color_cwd_root: theme.red,
          fish_color_user: theme.secondary,
          fish_color_host: theme.secondary,
          fish_color_host_remote: theme.orange,
          fish_color_status: theme.red,
          fish_pager_color_progress: "#{theme.primary} --bold",
          fish_pager_color_background: theme.dark? ? theme.bg : theme.terminal_bright_white,
          fish_pager_color_prefix: "#{theme.primary} --bold",
          fish_pager_color_completion: theme.fg,
          fish_pager_color_description: "#{theme.muted} --italics",
          fish_pager_color_secondary_background: theme.dark? ? theme.surface : theme.tab_bg,
          fish_pager_color_selected_background: theme.selection,
          fish_pager_color_selected_prefix: "#{theme.dark? ? theme.accent_secondary : theme.strong} --bold",
          fish_pager_color_selected_completion: theme.selection_fg,
          fish_pager_color_selected_description: theme.secondary
        }
        (["# #{theme.name} — generated by Lacold #{Lacold::VERSION}"] +
          colors.map { |key, value| "set -g #{key} #{value.to_s.split.map { |part| part.start_with?("--") ? part : bare(part) }.join(" ")}" }).join("\n")
      end
    end
  end
end
