# frozen_string_literal: true

module Lacold
  module Adapters
    class Fish < Base
      def id = "fish"
      def name = "Fish"
      def description = "Fish shell color configuration"

      def render(themes)
        files = themes.map { |theme| output("fish/#{theme.id}.fish", fish_theme(theme)) }
        files << output("fish/README.md", <<~MARKDOWN)
          # Lacold for Fish

          Source the chosen file from `~/.config/fish/config.fish`, or copy its
          `set -g` declarations into your existing configuration. Pair it with a
          Lacold terminal profile for the background and ANSI palette.
        MARKDOWN
      end

      private

      def fish_theme(theme)
        colors = {
          fish_color_normal: theme.fg,
          fish_color_command: theme.primary,
          fish_color_keyword: theme.strong,
          fish_color_quote: theme.fg,
          fish_color_redirection: theme.accent_secondary,
          fish_color_end: theme.strong,
          fish_color_error: theme.strong,
          fish_color_param: theme.fg,
          fish_color_comment: theme.muted,
          fish_color_selection: "#{theme.fg} --background=#{bare(theme.selection)}",
          fish_color_search_match: "#{theme.fg} --background=#{bare(theme.wash)}",
          fish_color_operator: theme.primary,
          fish_color_escape: theme.accent_secondary,
          fish_color_autosuggestion: theme.muted,
          fish_color_cancel: theme.strong,
          fish_color_valid_path: theme.fg,
          fish_pager_color_progress: theme.muted,
          fish_pager_color_prefix: theme.primary,
          fish_pager_color_completion: theme.fg,
          fish_pager_color_description: theme.muted,
          fish_pager_color_selected_background: "--background=#{bare(theme.selection)}"
        }
        (["# #{theme.name} — generated by Lacold #{Lacold::VERSION}"] +
          colors.map { |key, value| "set -g #{key} #{value.to_s.split.map { |part| part.start_with?("--") ? part : bare(part) }.join(" ")}" }).join("\n")
      end
    end
  end
end
