# frozen_string_literal: true

module Lacold
  module Adapters
    class Fzf < Base
      def id = "fzf"
      def name = "Fzf"
      def kind = "integration"
      def description = "Shell snippets that add Lacold colors to FZF_DEFAULT_OPTS"

      def render(themes)
        files = themes.map do |theme|
          output("fzf/#{theme.id}.sh", shell_theme(theme))
        end
        files << target_readme
      end

      private

      def shell_theme(theme)
        colors = {
          "bg" => theme.bg,
          "bg+" => theme.surface,
          "fg" => theme.secondary,
          "fg+" => theme.fg,
          "hl" => theme.accent_secondary,
          "hl+" => theme.primary,
          "info" => theme.muted,
          "marker" => theme.strong,
          "prompt" => theme.primary,
          "spinner" => theme.accent_faint,
          "pointer" => theme.strong,
          "header" => theme.accent_secondary,
          "border" => theme.border,
          "label" => theme.secondary,
          "query" => theme.fg
        }.map { |key, value| "#{key}:#{value}" }.join(",")
        <<~SH
          # #{theme.name} — generated by Lacold #{Lacold::VERSION}
          export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=#{colors}"
        SH
      end
    end
  end
end
