# frozen_string_literal: true

module Lacold
  module Adapters
    class Kitty < Base
      def id = "kitty"
      def name = "Kitty"
      def description = "Kitty theme configuration files"

      def render(themes)
        files = themes.map do |theme|
          output("kitty/#{theme.id}.conf", kitty_theme(theme))
        end
        files << output("kitty/README.md", <<~MARKDOWN)
          # Lacold for Kitty

          Copy a `.conf` file to `~/.config/kitty/themes/`, then run
          `kitten themes --reload-in=all Lacold` or include the file from
          `kitty.conf`.
        MARKDOWN
      end

      private

      def kitty_theme(theme)
        ansi = theme.ansi.values
        lines = [
          "# #{theme.name} — generated by Lacold #{Lacold::VERSION}",
          "background #{theme.bg}",
          "foreground #{theme.fg}",
          "selection_background #{theme.selection}",
          "selection_foreground #{theme.fg}",
          "cursor #{theme.primary}",
          "cursor_text_color #{theme.bg}",
          "url_color #{theme.primary}",
          "active_border_color #{theme.primary}",
          "inactive_border_color #{theme.border}",
          "active_tab_background #{theme.bg}",
          "active_tab_foreground #{theme.fg}",
          "inactive_tab_background #{theme.surface}",
          "inactive_tab_foreground #{theme.muted}",
          "bell_border_color #{theme.strong}"
        ]
        lines.concat(ansi.each_with_index.map { |color, index| "color#{index} #{color}" })
        lines.join("\n")
      end
    end
  end
end

