# frozen_string_literal: true

module Lacold
  module Adapters
    class Kitty < Base
      def id = "kitty"
      def name = "Kitty"
      def description = "Kitty theme configuration files"

      def render(themes)
        files = themes.map do |theme|
          output("kitty/#{theme.id}.conf", kitty_theme(theme))
        end
        theme_families(themes).select { |variants| complete_mode_pair?(variants) }.each do |variants|
          by_mode = variants.to_h { |theme| [theme.mode, theme] }
          directory = "kitty/auto/#{variants.first.family_id}"
          files << output("#{directory}/dark-theme.auto.conf", kitty_theme(by_mode.fetch(:dark)))
          files << output("#{directory}/light-theme.auto.conf", kitty_theme(by_mode.fetch(:light)))
          files << output("#{directory}/no-preference-theme.auto.conf", kitty_theme(by_mode.fetch(:light)))
        end
        files << output("kitty/README.md", <<~MARKDOWN)
          # Lacold for Kitty

          Copy a `.conf` file to `~/.config/kitty/themes/`, then run
          `kitten themes --reload-in=all Lacold` or include the file from
          `kitty.conf`.

          To follow the operating-system appearance automatically, copy the
          three files from the desired `auto/lacold-air-COLOR/` directory into
          `~/.config/kitty/` and restart Kitty.
        MARKDOWN
      end

      private

      def kitty_theme(theme)
        ansi = theme.ansi.values
        lines = [
          "# #{theme.name} — generated by Lacold #{Lacold::VERSION}",
          "background #{theme.bg}",
          "foreground #{theme.fg}",
          "selection_background #{theme.selection}",
          "selection_foreground #{theme.selection_fg}",
          "cursor #{theme.caret}",
          "cursor_text_color #{theme.bg}",
          "url_color #{theme.primary}",
          "active_border_color #{theme.primary}",
          "inactive_border_color #{theme.border}",
          "active_tab_background #{theme.bg}",
          "active_tab_foreground #{theme.selection_fg}",
          "inactive_tab_background #{theme.surface}",
          "inactive_tab_foreground #{theme.secondary}",
          "tab_bar_background #{theme.tab_bg}",
          "bell_border_color #{theme.orange}"
        ]
        lines.concat(ansi.each_with_index.map { |color, index| "color#{index} #{color}" })
        lines.join("\n")
      end
    end
  end
end
