# frozen_string_literal: true

module Lacold
  module Adapters
    class Nano < Base
      def id = "nano"
      def name = "Nano"
      def description = "GNU nano interface color settings"

      def render(themes)
        files = themes.map { |theme| output("nano/#{theme.id}.nanorc", nano_theme(theme)) }
        files << output("nano/README.md", <<~MARKDOWN)
          # Lacold for GNU nano

          Add `include /path/to/lacold-air-blue-dark.nanorc` to `~/.nanorc`.
          These files theme nano's interface; existing language syntax rules remain intact.
        MARKDOWN
      end

      private

      def pair(foreground, background = nil, bold: false, italic: false)
        attributes = []
        attributes << "bold" if bold
        attributes << "italic" if italic
        colors = [foreground, background].compact.join(",")
        ([attributes.join(","), colors].reject(&:empty?)).join(" ")
      end

      def nano_theme(theme)
        values = {
          titlecolor: pair(theme.fg, theme.raised, bold: true),
          statuscolor: pair(theme.fg, theme.surface),
          errorcolor: pair(theme.red, theme.surface, bold: true),
          selectedcolor: pair(theme.fg, theme.selection),
          stripecolor: pair(theme.fg, theme.line),
          numbercolor: pair(theme.line_nr, theme.bg),
          scrollercolor: pair(theme.primary, theme.surface),
          keycolor: pair(theme.primary, theme.surface, bold: true),
          functioncolor: pair(theme.fg, theme.surface),
          promptcolor: pair(theme.fg, theme.surface),
          minicolor: pair(theme.muted, theme.surface),
          spotlightcolor: pair(theme.fg, theme.wash)
        }
        (["# #{theme.name} — generated by Lacold #{Lacold::VERSION}"] +
          values.map { |key, value| "set #{key} #{value}" }).join("\n")
      end
    end
  end
end
