# frozen_string_literal: true

module Lacold
  module Adapters
    class Tmux < Base
      def id = "tmux"
      def name = "Tmux"
      def description = "Tmux status-line and pane styles"

      def render(themes)
        files = themes.map { |theme| output("tmux/#{theme.id}.conf", tmux_theme(theme)) }
        files << output("tmux/README.md", <<~MARKDOWN)
          # Lacold for Tmux

          Add `source-file /path/to/lacold-air-blue-dark.conf` to `.tmux.conf`,
          then reload with `tmux source-file ~/.tmux.conf`.
        MARKDOWN
      end

      private

      def tmux_theme(theme)
        <<~CONF
          # #{theme.name} — generated by Lacold #{Lacold::VERSION}
          set -g status-style "fg=#{theme.fg},bg=#{theme.surface}"
          set -g status-left-style "fg=#{theme.bg},bg=#{theme.primary},bold"
          set -g status-right-style "fg=#{theme.secondary},bg=#{theme.surface}"
          set -g window-status-style "fg=#{theme.muted},bg=#{theme.surface}"
          set -g window-status-current-style "fg=#{theme.primary},bg=#{theme.surface},bold"
          set -g pane-border-style "fg=#{theme.border}"
          set -g pane-active-border-style "fg=#{theme.primary}"
          set -g message-style "fg=#{theme.fg},bg=#{theme.selection}"
          set -g message-command-style "fg=#{theme.primary},bg=#{theme.surface}"
          set -g mode-style "fg=#{theme.fg},bg=#{theme.selection}"
          set -g clock-mode-colour "#{theme.primary}"
        CONF
      end
    end
  end
end
