# frozen_string_literal: true

module Lacold
  module Adapters
    class Zellij < Base
      def id = "zellij"
      def name = "Zellij"
      def description = "Zellij KDL theme definitions"

      def render(themes)
        files = themes.map { |theme| output("zellij/#{theme.id}.kdl", zellij_theme(theme)) }
        files << target_readme
      end

      private

      def zellij_theme(theme)
        ansi = theme.ansi
        entries = {
          fg: theme.fg, bg: theme.bg, black: ansi[:black], red: ansi[:red],
          green: ansi[:green], yellow: ansi[:yellow], blue: ansi[:blue],
          magenta: ansi[:magenta], cyan: ansi[:cyan], white: ansi[:white],
          orange: theme.orange
        }
        body = entries.map { |key, value| "        #{key} #{rgb_line(value)}" }.join("\n")
        <<~KDL
          // #{theme.name} — generated by Lacold #{Lacold::VERSION}
          themes {
              "#{theme.id}" {
          #{body}
              }
          }
        KDL
      end
    end
  end
end
